version: "3.7"

services:

  fastapi:
    build: .
    environment:
      REDIS_HOST: "redis"
      REDIS_PASSWORD: "password"
    ports:
      - "8000:8000"
    volumes:
      - "./:/code"
    depends_on:
      - "redis"
    command: ["--reload"]

  redis:
    image: sewenew/redis-protobuf:latest
    command: ["redis-server",  "--requirepass", "password"]
    ports:
      - "6379:6379"
    volumes:
      - "./orders.proto:/usr/lib/redis/proto/"
      #- "./redis.conf:/usr/lib/redis/conf/redis.conf"